language: perl
perl:
  - "5.8.1"
  - "5.8.2"
  - "5.8.3"
  - "5.8.4"
  - "5.8.5"
  - "5.8.6"
  - "5.8.7"
  - "5.8.8"
  - "5.8.9"
  - "5.10.0"
  - "5.10.1"
  - "5.12.2"
  - "5.12.3"
  - "5.12.4"
  - "5.12.5"
  - "5.14.0"
  - "5.14.1"
  - "5.14.2"
  - "5.14.2"
  - "5.14.3"
  - "5.14.4"
  - "5.16.0"
  - "5.16.1"
  - "5.16.2"
  - "5.16.3"
  - "5.18.0"
  - "5.18.1"
  - "5.18.2"
  - "5.20.0"
env:
  secure: "q9bwOsQvpvzcD4k0G4O1LhbhttABEtfFJAPC6+Kvompa7HqXF48MVf1c0protmI1+UcxPI78ooVMRUByhtnyCCh+pipeqmbSlixX0XtR2cAPI7XbjACqo4YVtoQTVkpDkIVQGeQ1Xkx5XYNttERUexUSQ187bUDvM5L6YtcJUk4="
before_install:
  - sudo apt-get update -qq
  - git clone git://github.com/haarg/perl-travis-helper ~/perl-travis-helper
  - source ~/perl-travis-helper/init
install:
  - true
script:
  - ./per-variant ./build
  - ./per-variant ./commit
after_success:
  - ./push $(./per-variant echo)
branches:
  only:
    - master
notifications:
  email: false
