language: perl
perl:
  - "5.8.8"
env:
  secure: "q9bwOsQvpvzcD4k0G4O1LhbhttABEtfFJAPC6+Kvompa7HqXF48MVf1c0protmI1+UcxPI78ooVMRUByhtnyCCh+pipeqmbSlixX0XtR2cAPI7XbjACqo4YVtoQTVkpDkIVQGeQ1Xkx5XYNttERUexUSQ187bUDvM5L6YtcJUk4="
before_install:
  - sudo apt-get update -qq
  - git clone git://github.com/haarg/perl-travis-helper ~/perl-travis-helper
  - source ~/perl-travis-helper/init
install:
  - ./per-variant ./build
script:
  - ./per-variant ./commit
after_success:
  - ./push $(./per-variant echo)
branches:
  only:
    - master
notifications:
  email: false
